services:
  db:
    image: postgres:latest
    ports:
      - "5431:5433"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080